name: main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: docker-self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          echo "Building version $(cat version) to be deployed to ${{ vars.HOST_MAIN }}"